//! Sans-io leadscrew control core, shared by every transport binary (BLE, TCP, ...).
//!
//! [`Link`] is the RESP command engine: it only knows about bytes in, bytes out -- no BLE, no
//! sockets. [`ControlLoop`] is the per-tick physics: it reads the spindle, derives the target
//! step rate from whatever [`Link`] last had commanded, and drives the carriage. Neither type
//! does any I/O; each transport binary is just a thin pump that feeds `Link::on_rx` with
//! whatever bytes it received, drains `Link::pending`/`Link::last_tx` out to the wire, and
//! calls [`ControlLoop::tick`] once per control tick.
//!
//! Architecture (see project conversation for the full derivation):
//! - The spindle encoder's extended position (`QuadratureDecoder::update`) is the single
//!   source of truth. There is no spindle index/Z pulse, so phase lock across threading passes
//!   relies entirely on never losing a count -- see the glitch filter set on the spindle by
//!   each transport binary.
//! - Every tick, `target_steps` is recomputed from scratch from the absolute spindle position,
//!   not accumulated -- this is a position-anchored (Bresenham-style) design, not a PID loop:
//!   any one tick's rounding/timing error is corrected by the next tick instead of drifting.
//! - Step pulses are generated by MCPWM (see [`crate::stepper`]), reconfigured to a new
//!   frequency each tick rather than bit-banged, so pulse timing within a tick is hardware-
//!   precise regardless of this loop's own jitter.
//! - An RPM x pitch interlock stops stepping if the selected ratio would demand a step rate
//!   beyond what's sane for the driver/motor -- see [`MAX_RPM_PITCH_UM`].

use core::fmt::Write as _;

use defmt::{error, info};
use esp_hal::mcpwm::PwmPeripheral;
use resp::{self, Command};

use crate::quadrature::QuadratureDecoder;
use crate::stepper::{Direction, StepGenerator};

/// Control loop tick rate, in Hz. Every transport binary's tick loop must run at this rate for
/// the RPM/step-rate math below to be correct.
pub const TICK_HZ: i64 = 1000;

/// Spindle encoder: 600 pulses/rev, x4 quadrature decode.
const SPINDLE_PPR: i64 = 600;
pub const SPINDLE_COUNTS_PER_REV: i64 = SPINDLE_PPR * 4;

/// Carriage drive: 5mm/rev ballscrew, 200 full-step/rev closed-loop stepper at 16x
/// microstepping.
const BALLSCREW_PITCH_UM: i64 = 5_000;
const MOTOR_FULL_STEPS_PER_REV: i64 = 200;
const MICROSTEPS: i64 = 16;
pub const MICROSTEPS_PER_REV: i64 = MOTOR_FULL_STEPS_PER_REV * MICROSTEPS;

/// Interlock ceiling on |RPM| x |ratio|, in RPM x micrometers. Above this, the requested ratio
/// would need a step rate that pushes the closed-loop stepper's shaft speed past a sane
/// torque-margin limit. 5000 RPM x mm keeps the motor shaft under ~1000 RPM at a 3mm/rev
/// pitch/this microstepping combination -- tune to your actual motor's torque-speed curve.
pub const MAX_RPM_PITCH_UM: i64 = 5_000_000;

/// Fixed jog rate (steps/sec) used by `MODE JOG` while `ENABLE`d -- ignores the spindle
/// entirely and just runs the stepper at a constant rate in the configured direction.
const JOG_STEPS_PER_SEC: u32 = 1600;

/// Command/status mode. `Feed` and `Thread` are mathematically identical (both track the
/// spindle at `ratio_um`) -- the distinction is purely what the operator is doing with it.
/// `Jog` ignores the spindle and runs at a fixed rate while enabled.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
enum Mode {
    Feed,
    Thread,
    Jog,
}

/// Everything the transport link needs to read or write, behind one `RefCell` (owned by the
/// transport binary) so I/O callbacks (which only get `&self`/shared captures) and the control
/// loop (plain code) can share it without unsafe.
pub struct Link {
    // Inbound line buffer.
    rx_line: [u8; 96],
    rx_len: usize,

    // Outbound: at most one frame in flight, drained by the transport once per tick. Replies
    // (from a completed command) and pushes (periodic/edge-triggered status) share this slot;
    // a reply is written here synchronously inside the write callback, so it goes out on the
    // *next* tick rather than the one that produced it -- fine, one tick is imperceptible for
    // a human typing commands.
    pub pending: Option<([u8; 128], usize)>,
    // Last frame actually sent, served back to a manual read instead of relying only on a
    // push/notify (not every client bothers to subscribe/poll before poking the link).
    pub last_tx: ([u8; 128], usize),

    // Commanded state, mutated only by parsed RESP commands.
    mode: Mode,
    ratio_um: i64,
    direction: Direction,
    enabled: bool,

    // Latest status snapshot, refreshed once per tick by the control loop, read by both the
    // periodic push and an on-demand `STATUS` command reply.
    rpm: i64,
    position: i64,
    target_steps: i64,
    fault: bool,
}

impl Default for Link {
    fn default() -> Self {
        Self::new()
    }
}

impl Link {
    pub const fn new() -> Self {
        Self {
            rx_line: [0; 96],
            rx_len: 0,
            pending: None,
            last_tx: ([0; 128], 0),
            mode: Mode::Feed,
            ratio_um: 0,
            direction: Direction::Forward,
            enabled: false,
            rpm: 0,
            position: 0,
            target_steps: 0,
            fault: false,
        }
    }

    /// Formats the shared status payload: `RPM=<n> POS=<n> TARGET=<n> STATE=<RUN|OFF|FAULT>`.
    fn format_status<'a>(&self, buf: &'a mut [u8]) -> &'a str {
        let mut w = FixedWriter::new(buf);
        let state = if self.fault {
            "FAULT"
        } else if self.enabled {
            "RUN"
        } else {
            "OFF"
        };
        let _ = write!(
            w,
            "RPM={} POS={} TARGET={} STATE={}",
            self.rpm, self.position, self.target_steps, state
        );
        w.finish()
    }

    /// Queues a reply/push frame built from `payload` via `encode` (one of
    /// `resp::write_ok`/`write_err`/`write_bulk`/`write_push`, partially applied).
    fn queue(&mut self, encode: impl FnOnce(&mut [u8]) -> Option<usize>) {
        let mut buf = [0u8; 128];
        if let Some(len) = encode(&mut buf) {
            self.pending = Some((buf, len));
        }
    }

    /// Handles one complete command line, mutating state and queuing a reply.
    fn handle_line(&mut self, line: &str) {
        let cmd = Command::parse(line);
        match cmd.name() {
            "MODE" => {
                if self.enabled {
                    self.queue(|b| resp::write_err(b, "busy, DISABLE first"));
                    return;
                }
                match cmd.arg(0) {
                    Some("FEED") => {
                        self.mode = Mode::Feed;
                        self.queue(resp::write_ok);
                    }
                    Some("THREAD") => {
                        self.mode = Mode::Thread;
                        self.queue(resp::write_ok);
                    }
                    Some("JOG") => {
                        self.mode = Mode::Jog;
                        self.queue(resp::write_ok);
                    }
                    _ => self.queue(|b| resp::write_err(b, "bad mode")),
                }
            }
            "RATIO" => {
                if self.enabled {
                    self.queue(|b| resp::write_err(b, "busy, DISABLE first"));
                    return;
                }
                match cmd
                    .arg(0)
                    .and_then(|a| {
                        a.parse::<i64>()
                            .ok()
                    }) {
                    Some(um) if um >= 0 => {
                        self.ratio_um = um;
                        self.queue(resp::write_ok);
                    }
                    _ => self.queue(|b| resp::write_err(b, "bad ratio")),
                }
            }
            "DIR" => match cmd.arg(0) {
                Some("FWD") => {
                    self.direction = Direction::Forward;
                    self.queue(resp::write_ok);
                }
                Some("REV") => {
                    self.direction = Direction::Reverse;
                    self.queue(resp::write_ok);
                }
                _ => self.queue(|b| resp::write_err(b, "bad dir")),
            },
            "ENABLE" => {
                self.enabled = true;
                self.queue(resp::write_ok);
            }
            "DISABLE" => {
                self.enabled = false;
                self.queue(resp::write_ok);
            }
            "STATUS" => {
                let mut status_buf = [0u8; 96];
                let status = self.format_status(&mut status_buf);
                self.queue(|b| resp::write_bulk(b, status));
            }
            _ => self.queue(|b| resp::write_err(b, "unknown command")),
        }
    }

    /// Feeds newly-received bytes in, splitting on `\n` and handling each complete line.
    pub fn on_rx(&mut self, data: &[u8]) {
        for &byte in data {
            if byte == b'\n' {
                let mut end = self.rx_len;
                if end > 0 && self.rx_line[end - 1] == b'\r' {
                    end -= 1;
                }
                // Copy out before resetting rx_len/calling handle_line, so the borrow of the
                // line doesn't overlap with the &mut self that handle_line needs.
                let mut line_buf = [0u8; 96];
                line_buf[..end].copy_from_slice(&self.rx_line[..end]);
                self.rx_len = 0;
                if let Ok(line) = core::str::from_utf8(&line_buf[..end])
                    && !line.is_empty()
                {
                    self.handle_line(line);
                }
            } else if self.rx_len
                < self
                    .rx_line
                    .len()
            {
                self.rx_line[self.rx_len] = byte;
                self.rx_len += 1;
            } else {
                // Line too long for the buffer -- drop it rather than silently truncating.
                self.rx_len = 0;
            }
        }
    }

    /// Queues a status push if nothing else is already queued -- called by [`ControlLoop::tick`]
    /// on its own periodic schedule, or by a transport wanting an immediate push (e.g. on an
    /// interlock edge).
    fn queue_status_push_if_idle(&mut self) {
        if self
            .pending
            .is_none()
        {
            let mut status_buf = [0u8; 96];
            let status = self.format_status(&mut status_buf);
            self.queue(|b| resp::write_push(b, status));
        }
    }
}

/// A tiny `core::fmt::Write` sink over a fixed byte buffer, for building short status strings
/// with no heap allocation.
struct FixedWriter<'a> {
    buf: &'a mut [u8],
    len: usize,
}

impl<'a> FixedWriter<'a> {
    fn new(buf: &'a mut [u8]) -> Self {
        Self { buf, len: 0 }
    }

    /// Consumes the writer to hand back a `&'a str` tied to the original buffer's lifetime
    /// rather than to this (local) writer struct's.
    fn finish(self) -> &'a str {
        core::str::from_utf8(&self.buf[..self.len]).unwrap_or("")
    }
}

impl core::fmt::Write for FixedWriter<'_> {
    fn write_str(&mut self, s: &str) -> core::fmt::Result {
        let bytes = s.as_bytes();
        if self.len + bytes.len()
            > self
                .buf
                .len()
        {
            return Err(core::fmt::Error);
        }
        self.buf[self.len..self.len + bytes.len()].copy_from_slice(bytes);
        self.len += bytes.len();
        Ok(())
    }
}

/// Owns the spindle encoder and stepper drive, and derives per-tick motion from a [`Link`]'s
/// commanded state -- shared verbatim between every transport binary, since the physics don't
/// care how commands arrived.
pub struct ControlLoop<'d, const UNIT: usize, PWM, const TIM: u8, const OP: u8> {
    spindle: QuadratureDecoder<'d, UNIT>,
    carriage: StepGenerator<'d, PWM, TIM, OP>,
    last_position: i64,
    steps_emitted: i64,
    fault: bool,
    push_countdown: u32,
}

impl<'d, const UNIT: usize, PWM: PwmPeripheral, const TIM: u8, const OP: u8>
    ControlLoop<'d, UNIT, PWM, TIM, OP>
{
    pub fn new(
        spindle: QuadratureDecoder<'d, UNIT>,
        carriage: StepGenerator<'d, PWM, TIM, OP>,
    ) -> Self {
        Self {
            spindle,
            carriage,
            last_position: 0,
            steps_emitted: 0,
            fault: false,
            push_countdown: 0,
        }
    }

    /// Advances the control loop by one tick: reads the spindle, derives target steps from
    /// `link`'s commanded mode/ratio/direction/enabled, drives the carriage, and writes the
    /// resulting rpm/position/target_steps/fault back into `link`. Call this once per tick
    /// (see [`TICK_HZ`]) regardless of transport.
    pub fn tick(&mut self, link: &mut Link) {
        let (mode, ratio_um, direction, enabled) =
            (link.mode, link.ratio_um, link.direction, link.enabled);

        let position = self
            .spindle
            .update();
        let delta = position - self.last_position;
        self.last_position = position;
        let rpm = delta * 60 * TICK_HZ / SPINDLE_COUNTS_PER_REV;

        let signed_ratio_um = match direction {
            Direction::Forward => ratio_um,
            Direction::Reverse => -ratio_um,
        };
        let now_fault =
            rpm.unsigned_abs() * signed_ratio_um.unsigned_abs() > MAX_RPM_PITCH_UM as u64;
        if now_fault && !self.fault {
            error!(
                "interlock tripped: {} RPM x {} um ratio exceeds {} RPM*um limit",
                rpm, signed_ratio_um, MAX_RPM_PITCH_UM
            );
        } else if !now_fault && self.fault {
            info!("interlock cleared");
        }
        self.fault = now_fault;

        let target_steps = if mode == Mode::Jog {
            // Jog ignores the spindle; steps_emitted just chases a fixed rate below.
            self.steps_emitted
        } else {
            (position * signed_ratio_um * MICROSTEPS_PER_REV)
                / (BALLSCREW_PITCH_UM * SPINDLE_COUNTS_PER_REV)
        };

        // While disabled (or faulted), keep steps_emitted pinned to the current target so
        // re-enabling never tries to "catch up" on motion that happened while declutched --
        // that would be a sudden, unsafe burst. This is exactly a mechanical clutch's behavior.
        if !enabled || self.fault {
            self.steps_emitted = target_steps;
        }

        let (steps_per_sec, step_direction) = if !enabled || self.fault {
            (0u32, Direction::Forward)
        } else if mode == Mode::Jog {
            (JOG_STEPS_PER_SEC, direction)
        } else {
            let step_delta = target_steps - self.steps_emitted;
            if step_delta == 0 {
                (0u32, Direction::Forward)
            } else {
                let step_direction = if step_delta > 0 {
                    Direction::Forward
                } else {
                    Direction::Reverse
                };
                let rate = (step_delta.unsigned_abs() as u32).saturating_mul(TICK_HZ as u32);
                (rate, step_direction)
            }
        };

        match self
            .carriage
            .set_rate(steps_per_sec, step_direction)
        {
            Ok(()) => {
                if steps_per_sec != 0 && mode != Mode::Jog {
                    self.steps_emitted = target_steps;
                } else if mode == Mode::Jog {
                    let signed_rate = match step_direction {
                        Direction::Forward => steps_per_sec as i64,
                        Direction::Reverse => -(steps_per_sec as i64),
                    };
                    self.steps_emitted += signed_rate / TICK_HZ;
                }
            }
            Err(_) => {
                error!("step rate {} Hz out of range, stopping", steps_per_sec);
                self.carriage
                    .stop();
            }
        }

        // Refresh the shared status snapshot and, if nothing else is queued, push it out
        // periodically (~5Hz).
        link.rpm = rpm;
        link.position = position;
        link.target_steps = target_steps;
        link.fault = self.fault;

        self.push_countdown += 1;
        let due = self.push_countdown >= 200;
        if due {
            self.push_countdown = 0;
            link.queue_status_push_if_idle();
        }
    }
}
